completed string-manipulation-2 | Daniel Hong
daniel-sj-hong/c0621-code-solutions pull request #44
Opened 2021-07-07 02:29 UTC by daniel-sj-hong

![Capture](https://user-images.githubusercontent.com/80491609/124691271-6b319300-de90-11eb-85ea-824c62ee0eef.PNG)

2021-07-07 17:54 UTC, codingcodymiller requested changes
Hey dude! Please resubmit with your pseudocode included for each function you defined

2021-08-13 22:05 UTC, thebearingedge requested changes

2021-08-13 22:05 UTC, thebearingedge commented on string-manipulation-2/src/first-chars.js
> +  }
I recommend doing this right after `container` is declared. It's good to get the special cases like this out of the way near the top of the function

2021-08-13 22:05 UTC, thebearingedge commented on string-manipulation-2/src/last-chars.js
> +  }
Same here

2021-08-13 22:05 UTC, thebearingedge commented on string-manipulation-2/src/truncate.js
> +  }
And here

2021-08-14 14:24 UTC, thebearingedge approved these changes

2021-08-15 02:58 UTC, merged