completed javascript-typing-tutor | Daniel Hong
daniel-sj-hong/c0621-code-solutions pull request #51
Opened 2021-07-09 03:35 UTC by daniel-sj-hong

![gif1](https://user-images.githubusercontent.com/80491609/125019507-0ca11c00-e02c-11eb-8cf5-255d958b930f.gif)

2021-07-09 17:48 UTC, codingcodymiller requested changes
Great start here!! One note for you:

2021-07-09 17:48 UTC, codingcodymiller commented on javascript-typing-tutor/main.js
> +}
Uh-oh! `location.reload()` should be avoided at all costs, it is completely reloading your page, which is a huge tank to your efficiency in your code. Instead, you should reset the value of the variables and DOM elements to their original setup when the page loaded.

2021-07-09 18:44 UTC, daniel-sj-hong commented
![gif1](https://user-images.githubusercontent.com/80491609/125123011-fdad7e80-e0aa-11eb-820f-7a752d18f58c.gif)

2021-07-12 17:44 UTC, codingcodymiller approved these changes

2021-07-19 22:28 UTC, merged